# Generated by Django 3.1.1 on 2020-09-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chanpin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('jiage', models.CharField(max_length=30)),
                ('zhonglei', models.CharField(choices=[('shiwai', 'shiwai'), ('shinei', 'shinei')], max_length=30)),
                ('miaoshu', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='maijia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dianhua', models.CharField(max_length=30)),
                ('emal', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dingdan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('zhuangtai', models.CharField(choices=[('等待', '等待'), ('正在', '正在'), ('送达', '送达')], max_length=30)),
                ('chanpin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_dingdan', to='app1.chanpin')),
                ('maijia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_dingdan', to='app1.maijia')),
            ],
        ),
    ]
